Fix ESLint not working on VSCode #1128
t3-oss/create-t3-turbo pull request #1143
Opened 2024-08-09 21:31 UTC by smblee

2024-08-09 21:39 UTC, juliusmarminge requested changes
What Node version are you on? `import.meta.dirname` is available on 20.11 and later: https://nodejs.org/api/esm.html#importmetadirname

2024-08-09 22:39 UTC, smblee commented
@juliusmarminge Good call out. I am on v20.15.1 but looks like ESLint plugin in VSCode is using v20.9.0. Wonder how the ESLint plugin is pulling the node to use

2024-08-12 01:11 UTC, smblee commented
@juliusmarminge 
As i noted here: https://github.com/t3-oss/create-t3-turbo/issues/1128

VSCode ESLint is kinda finicky in that it doesn't have a good way to set the node version (like matching the proj environment node config)

This suggested change might be good to be compatible with older versions of Node? Otherwise it just becomes a silent failure until you notice it

2024-08-14 18:56 UTC, juliusmarminge approved these changes

2024-08-14 19:00 UTC, merged