feat: base preset for tailwind
t3-oss/create-t3-turbo pull request #57
Opened 2022-11-07 13:52 UTC by rndy28

2022-11-07 14:30 UTC, juliusmarminge requested changes

2022-11-07 14:39 UTC, rndy28 commented on apps/nextjs/tailwind.config.cjs
> +  presets: [require("@acme/tailwind-config")],
yah, you can do that, reason why i do that because just in case i need to have separate plugin between next and expo

2022-11-07 14:42 UTC, rndy28 commented on apps/nextjs/next.config.mjs
> +    transpilePackages: ["@acme/api", "@acme/auth", "@acme/db", "@acme/tailwind-config"],
> Don't think this needs to be transpiled

ok

2022-11-07 15:40 UTC, juliusmarminge commented on apps/nextjs/tailwind.config.cjs
> +  presets: [require("@acme/tailwind-config")],
Oh that actually makes sense.

2022-11-08 00:32 UTC, juliusmarminge approved these changes

2022-11-08 00:33 UTC, merged